Import("*")
SimObject('SplitAdapter.py',
        sim_objects=['SplitCPUAdapter', 'SplitMEMAdapter'])

Source('split_cpu_adapter.cc')
Source('split_mem_adapter.cc')

DebugFlag('SplitCPUAdapter')
DebugFlag('SplitMEMAdapter')
